---
format: html
---

In this study, we used Bayesian Networks (BNs) to predict whether individuals earn more than $50,000 annually, using the Adult Income Dataset, which includes various demographic and employment-related attributes such as age, education, work class, marital status, occupation, race, sex, capital gain, capital loss, hours per week, and native country. Our main goal was to identify key factors influencing income levels through dependencies among these variables.

Our analysis yielded several key findings. Higher education levels correlate with a higher probability of earning more than $50,000 annually. Individuals with advanced degrees have significantly higher probabilities of high income, underlining the importance of education in determining income. There are notable gender disparities in income. Males generally have higher probabilities of earning over $50,000 across various education levels and occupations compared to females, highlighting the persistent gender wage gap. Occupation directly influences income levels. High-income probabilities are associated with roles such as executive-managerial and professional specialty, while lower-paying occupations show much lower probabilities of high income. Age significantly affects income distribution. Younger individuals (aged 18 to 39) are more likely to earn less than $50,000, while middle-aged individuals (aged 40 to 64) have higher probabilities of earning over $50,000, reflecting career progression and work experience.

Despite these insights, BNs are arguably not the strongest in prediction power. The confusion matrix for our predictions showed that the model has an overall accuracy of 81.27%. This indicates that while BNs offer valuable insights and detailed conditional probability tables (CPTs), their predictive accuracy may be more limited compared to other methods.

In conclusion, Bayesian Networks are useful for understanding factors influencing income levels and providing interpretable probabilistic dependencies. Although their predictive power is not the best, their ability to explain complex relationships through conditional probabilities makes them a valuable tool for a wide variety of sciences. Future work should explore integrating BNs with other modeling techniques to improve predictive performance while maintaining their interpretative strengths, thereby enhancing their utility in data-driven decision-making across various fields.
