---
title: "Predicting Income with Bayesian Networks: A Case Study Using the Adult Income Dataset - Data Science Capstone"
author: "Michael Zeihen, Maxime Martin, Sarah Burns, Seth Henry"
date: '`r Sys.Date()`'
format:
  html:
    code-fold: true
    #backgroundcolor: "#ffd8ae"
course: STA 6257 - Advanced Statistical Modeling
bibliography: references.bib # file contains bibtex for references
#always_allow_html: true # this allows to get PDF with HTML features
self-contained: true
execute: 
  warning: false
  message: false
editor: 
  markdown: 
    wrap: 72
toc: true
toc-title: "Table of Contents"
toc-depth: 3 
---

[Dataset & Summaries](Reference_Summaries.html)<br>
[Slides](Slides.html)<br>

```{r, warning=FALSE, echo=T, message=FALSE}
# loading packages 
library(rmarkdown)
library(tidyverse)
library(knitr)
library(ggthemes)
library(ggrepel)
library(dslabs)
library(datasets)
library(ggplot2)
library(cluster)
library(bnlearn)
library(e1071)
library(Rgraphviz)
library(tidyr)
library(dplyr)

```

# I Introduction

```{r, child='_Introduction_section.qmd'}

```

# II Methodology

```{r, child='_Methodology_section.qmd'}

```

# III Analyse and visualisation

```{r, child='_DataVisual_section.qmd'}

```

# IV Conclusion

```{r, child='_Conclusion_section.qmd'}

```

# References
